### PR TITLE
[UPDATED] Dependency to NATS v1.11.0

### PR DESCRIPTION
**Pull request by kozlovic**
Also updated the tests dependencies to NATS server v2.2.5 and
NATS Streaming current main branch (that has its dependencies
to NATS Server and other updated).

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
@wallyqs I would like your opinion. I have updating NATS Streaming servers dependencies but have not yet released. I am now updating stan.go library that uses a test mod file and reference the streaming server's main branch. I was going to release the client, say stan.go:v0.9.0, and then update the streaming server's go.mod to stan.go:v0.9.0 and then release as v0.22.0. The question is: would you do it this way, or first release streaming server v0.22.0 with dep on stan.go:v0.8.3, and then update stan.go with streaming v0.22.0 deps? Both would work, just would like to have someone else take on that?

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by wallyqs** [comment]
Either seems fine but since for the stan.go the server it is only a test dependency I think sounds better to release first the client and then tag the nats-streaming-server with stan.go:v0.9.0

**Comment by kozlovic** [comment]
@wallyqs Thanks. But to be clear, the streaming server has nats.go as a dependency for the server code itself, but does not have stan.go as a dependency, just as a test dependency. It just happens that I do not have separate go.mod and go_tests.mod for the server.

**Comment by wallyqs** [comment]
@kozlovic yes understand that part, I've found that splitting test deps from go.mod into go_test.mod can be tricky to get right in projects that use vendor because of how `go mod vendor` works, so single go.mod for now might be easier to work with for the servers

**Pull request merged**
