### PR TITLE
[ADDED] RedeliveryCount in PubMsg

### PR DESCRIPTION
**Pull request by kozlovic**
This is the first step to support server setting a RedeliveryCount
in PubMsg when those are redelivered.
See https://github.com/nats-io/nats-streaming-server/issues/728

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
@bmcstdio @sujeshthekkepatt @kell18 If you could have a look at this. This is the first step to have support in the server (the protobuf is actually hosted in here and vendored in the server).
Is `RedeliveryCount` name ok? Also, I made it a `uint32`, any suggestion as to what type would work better?

**Comment by sujeshthekkepatt** [comment]
@kozlovic Great to see this PR!! The name `RedeliveryCount` seems perfect for this. Also, I am not a go developer, but should we convert the type into an `uint16`? Isn't `uint32` a little higher? Otherwise it great to see this PR and looking forward to using it. And can we expect persisted `RedeliveryCount` any time soon :) ?

**Comment by sujeshthekkepatt** [comment]
LGTM

**Comment by kell18** [comment]
LGTM! 👍

**Pull request merged**
